### ISSUE TITLE
javah: No such file or directory Windows 10, Java 12

### ISSUE THREAD

**Issue by Phylloxera** [s-u/rJava#176] opened 2019-03-27 14:54 UTC
Hello,
I installed the 64bit jdk (version12) and 32bit jdk (version8). Then opened RStudio and entered
```
Sys.setenv(JAVA_HOME="C:/Program Files/Java/jdk-12")
install.packages("rJava",,"http://rforge.net")
```
The last 13 lines of the error are:
```
if [ -n "C:/PROGRA~1/Java/jdk-12/bin/javah" ]; then C:/PROGRA~1/Java/jdk-12/bin/javah -d . -classpath . org.rosuda.JRI.Rengine; fi
sh: C:/PROGRA~1/Java/jdk-12/bin/javah: No such file or directory
make[1]: *** [Makefile.all:14: org_rosuda_JRI_Rengine.h] Error 127
make[1]: Leaving directory '/Users/AARON~1.DIC/AppData/Local/Temp/RtmpQnKbA9/R.INSTALL2d98240f777/rJava/jri/src'
make: *** [Makefile.all:19: src/JRI.jar] Error 2
**** WARNING: JRI could NOT be built
Set IGNORE=1 if you want to build rJava anyway.
ERROR: configuration failed for package 'rJava'
* removing 'C:/Program Files/R/R-3.5.3/library/rJava'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘rJava’ had non-zero exit status
```
Please help!

**Comment by s-u** [comment] 2019-03-27 15:13
This is a duplicate of  #157 - please see the suggested fix there and report there - I'lll close this as duplicate.

Also please note that JDK-12 has broken JNI (see #175) so it doesn't work. Stick with JDK-11 until Oracle fixes JDK-12.

**Closed by s-u** 2019-03-27 15:13 UTC
