### ISSUE TITLE
rJava fails to deal with JVMTI

### ISSUE THREAD

**Issue by mohanr** [s-u/rJava#18] opened 2014-06-17 17:20 UTC
I use rJava and call Java code that uses JVMTI code like this

```
   VM vm = VM.getVM();
    Universe universe = vm.getUniverse();
     CollectedHeap heap = universe.heap();
```

rJava does not call this code directly but calls a method that in turn internally uses JVMTI.

This code attaches to another JVM and to get its internals. This is legal Java and it works when tested separately. But when I use rJava to call this code, the call is successful but it throws an error. I believe there  is Java native Interface involved in the JVM and it seems to affect R. rJava is 0.9

version
                _
platform       x86_64-apple-darwin10.8.0
arch           x86_64
os             darwin10.8.0
system         x86_64, darwin10.8.0
status
major          3
minor          1.0
year           2014
month          04
day            10
svn rev        65387
language       R
version.string R version 3.1.0 (2014-04-10)
nickname       Spring Dance

Error: C stack usage  140730070087404 is too close to the limit
Error: C stack usage  140730070156700 is too close to the limit
Warning: stack imbalance in '.Call', 59 then -1
Warning: stack imbalance in '{', 56 then -4

  **\* caught bus error ***
address 0x100583fd8, cause 'non-existent physical address'

  **\* caught bus error ***
address 0x100583fd8, cause 'non-existent physical address'

Traceback:
  1: run(timeoutMs)
  2: service(timeout)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: run(10)

  **\* caught segfault ***
address 0x20057ea40, cause 'memory not mapped'

Traceback:
  1: run(timeoutMs)
  2: service(timeout)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by s-u** [comment] 2022-01-22 04:48
The above is incomplete since something has to load and run the tool and that's likely where the problem is (just calling `run()` from R yield `VM.initialize() was not yet called`). This API has been very badly documented and AFAICS has removed from latest JDKs so I'm closing this as probably nothing to do with rJava.

**Closed by s-u** 2022-01-22 04:48 UTC
