### ISSUE TITLE
Multiple Rengine objects per JVM

### ISSUE THREAD

**Issue by colomb001** [s-u/rJava#45] opened 2015-05-29 20:33 UTC
I'm running JUnit tests against some code that leverages JRI to load and run some R scripts. Each unit test creates an Rengine object, loads a script and runs it, checks the output, then calls Rengine.end(). Unfortunately, only the first instance of the Rengine seems to work. Depending on the version of R, any Rengine instance created after the first Rengine.end() will either hang the JVM or no be able to source the scripts I want to test.

    public void testR()
    {
        Rengine r = new Rengine( new String[]{ "--no-save" }, false, null );
        r.eval( "setwd(\"C:/temp/\")" );
        REXP rexp = r.eval( "getwd()" );
        System.out.println( "rexp = " + rexp );
        rexp = r.eval( "source(\"calcBeta.R\")" );
        System.out.println( "rexp = " + rexp );
        r.end();

        r = new Rengine( new String[]{ "--no-save" }, false, null );
        r.eval( "setwd(\"C:/temp/\")" );
        rexp = r.eval( "getwd()" );
        System.out.println( "rexp = " + rexp );
        rexp = r.eval( "source(\"calcBeta.R\")" );
        System.out.println( "rexp = " + rexp );
        r.end();
    }

If run against R 3.0.1 in windows, the second engine instance will return null when sourcing the script. When run against R 3.1.3 or later, it will just hang when trying to instantiate the second Rengine. Both are running using rJava 0.9-6

Is there a preferred way to shutdown the Rengine object to allow a new one to be instantiated within the same JVM?

Thanks

**Comment by s-u** [comment] 2015-05-29 20:38
There is no way to shutdown R - it only supports single instantiation, so you have to make sure you share the previous instance. This is a duplicate of #12

**Closed by s-u** 2015-05-29 20:38 UTC
Labels: duplicate

**Comment by colomb001** [comment] 2015-05-29 20:44
Sorry, didn't peruse the closed issues. Thanks for the quick reply.
